### ISSUE TITLE
Destroyed instances of `Validation` must be collected by GC

### ISSUE THREAD

**Issue by Devoter** [vueent/vueent#23]
A `WeakMap` which is injected into `Provider` and keeps references to instances can be used. After some destructions, the number of items in the WeakMap should be reduced. Maybe, the provider reference is have to be cleared inside the destroyed `Validation`instance to resolve the issue.

**Comment by EYE5** [comment]
During testing it turned out that the memory leak problem only occurs when vueent is used without a vue instance, i.e. in normal use case, there should be no problems.

[https://github.com/vuejs/composition-api/issues/270](https://github.com/vuejs/composition-api/issues/270)
